import crypto from 'node:crypto';
const MILES_TO_KM = 1.609344;
const iso = value => Number.isFinite(Number(value)) ? new Date(Number(value) * 1000).toISOString() : null;
const numberOrNull = value => value === null || value === undefined || value === '' || !Number.isFinite(Number(value)) ? null : Number(value);
const hash = payload => crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex');
function statusAt(changes, status) { return iso((Array.isArray(changes) ? changes : []).find(change => change?.status === status)?.timestamp); }
export function normalizeTrip(trip) {
  const distanceMiles = numberOrNull(trip?.distance);
  return { schema_version: 1, source: 'uber_driver_api', source_trip_id: trip?.trip_id ?? null, source_driver_id: trip?.driver_id ?? null, source_vehicle_id: trip?.vehicle_id ?? null, status: trip?.status ?? null, accepted_at: statusAt(trip?.status_changes, 'accepted'), driver_arrived_at: statusAt(trip?.status_changes, 'driver_arrived'), trip_began_at: statusAt(trip?.status_changes, 'trip_began'), completed_at: statusAt(trip?.status_changes, 'completed'), pickup_at: iso(trip?.pickup?.timestamp), dropoff_at: iso(trip?.dropoff?.timestamp ?? trip?.drop_off?.timestamp), duration_seconds: numberOrNull(trip?.duration), distance_miles: distanceMiles, distance_km: distanceMiles === null ? null : Number((distanceMiles * MILES_TO_KM).toFixed(3)), fare_gross: numberOrNull(trip?.fare), currency: trip?.currency_code ?? null, surge_multiplier: numberOrNull(trip?.surge_multiplier), start_city: trip?.start_city ? { display_name: trip.start_city.display_name ?? null, latitude: numberOrNull(trip.start_city.latitude), longitude: numberOrNull(trip.start_city.longitude) } : null, route: { pickup_location: null, dropoff_location: null, polyline: null, provenance: 'not_exposed_by_uber_driver_api' }, operational: { distance_to_pickup_km: null, deadhead_after_trip_km: null, total_operational_distance_km: null, provenance: 'requires_motoristaops_telemetry' }, raw_sha256: hash(trip) };
}
export function normalizePayment(payment) { return { schema_version: 1, source: 'uber_driver_api', source_payment_id: payment?.payment_id ?? null, source_trip_id: payment?.trip_id ?? null, category: payment?.category ?? null, event_at: iso(payment?.event_time), net_payout: numberOrNull(payment?.amount), cash_collected: numberOrNull(payment?.cash_collected), currency: payment?.currency_code ?? null, breakdown: { toll: numberOrNull(payment?.breakdown?.toll), service_fee: numberOrNull(payment?.breakdown?.service_fee), other: numberOrNull(payment?.breakdown?.other), rider_split_fare: numberOrNull(payment?.rider_fees?.split_fare) }, raw_sha256: hash(payment) }; }
const sumNullable = values => { const numeric = values.filter(v => v !== null && v !== undefined && Number.isFinite(Number(v))).map(Number); return numeric.length ? Number(numeric.reduce((a,b)=>a+b,0).toFixed(2)) : null; };
export function buildReviewPayload(rawTrips, rawPayments, metadata = {}) {
  const trips = rawTrips.map(normalizeTrip); const payments = rawPayments.map(normalizePayment); const groups = new Map();
  for (const p of payments) { if (!p.source_trip_id) continue; const g = groups.get(p.source_trip_id) || []; g.push(p); groups.set(p.source_trip_id, g); }
  const paymentMap = new Map([...groups.entries()].map(([id, items]) => [id, { source_trip_id: id, line_items: items.length, net_payout: sumNullable(items.map(i=>i.net_payout)), cash_collected: sumNullable(items.map(i=>i.cash_collected)), toll: sumNullable(items.map(i=>i.breakdown?.toll)), service_fee: sumNullable(items.map(i=>i.breakdown?.service_fee)), other: sumNullable(items.map(i=>i.breakdown?.other)), currency: items.find(i=>i.currency)?.currency ?? null }]));
  const enrichedTrips = trips.map(t => ({ ...t, payment: t.source_trip_id ? paymentMap.get(t.source_trip_id) ?? null : null, reconciliation_status: t.source_trip_id && paymentMap.has(t.source_trip_id) ? 'matched' : 'missing_payment' }));
  return { schema_version: 1, source: 'uber_driver_api', generated_at: new Date().toISOString(), review_required: true, persistence_status: 'not_persisted', metadata, trips: enrichedTrips, payments, summary: { trips: enrichedTrips.length, payments: payments.length, matched_trips: enrichedTrips.filter(t=>t.reconciliation_status==='matched').length, gross_fare: sumNullable(enrichedTrips.map(t=>t.fare_gross)), net_payout: sumNullable([...paymentMap.values()].map(i=>i.net_payout)), distance_km: Number(enrichedTrips.reduce((a,t)=>a+(t.distance_km||0),0).toFixed(3)) } };
}
