/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface PresenceDriverPages {
  orderId: Int8;
  publicationStatus: Generated<string>;
  publishedAt: Timestamp | null;
  publishedHash: string | null;
  publishedVersion: number | null;
  slug: string;
  updatedAt: Generated<Timestamp>;
  userId: Int8;
}

export interface PresenceGoogleBusiness {
  connectionStatus: Generated<string>;
  mode: Generated<string>;
  orderId: Int8;
}

export interface PresenceInventoryItems {
  itemCode: string;
  leadTimeDays: number | null;
  quantityOnHand: number | null;
  reorderPoint: number | null;
  supplier: string | null;
  unitCostCents: number | null;
  updatedAt: Generated<Timestamp>;
}

export interface PresenceOrderBomSnapshot {
  createdAt: Generated<Timestamp>;
  itemCode: string;
  label: string;
  orderId: Int8;
  personalized: Generated<boolean>;
  quantity: number;
  unitCostCents: number | null;
}

export interface PresenceOrderEvents {
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  orderId: Int8;
  publicMessage: string | null;
  state: string;
}

export interface PresenceOrderPersonalizations {
  displayName: string;
  orderId: Int8;
  shortServiceLine: string | null;
  whatsapp: string;
}

export interface PresenceOrders {
  amountCents: number | null;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<Int8>;
  productSku: string | null;
  productVersion: number | null;
  state: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: Int8;
}

export interface PresencePackageSpecs {
  heightCm: Numeric | null;
  insuranceValueCents: number | null;
  lengthCm: Numeric | null;
  productSku: string;
  productVersion: number;
  source: string | null;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
  weightKg: Numeric | null;
  widthCm: Numeric | null;
}

export interface PresencePaymentAttempts {
  amountCents: number;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  id: Generated<Int8>;
  idempotencyKey: string;
  orderId: Int8;
  provider: Generated<string>;
  providerOrderId: string | null;
  status: string;
  updatedAt: Generated<Timestamp>;
}

export interface PresencePaymentWebhookEvents {
  createdAt: Generated<Timestamp>;
  externalEventId: string;
  id: Generated<Int8>;
  payload: Json;
  payloadHash: string;
  processedAt: Timestamp | null;
  processingResult: string | null;
  provider: string;
  providerOrderId: string | null;
  signatureValid: boolean;
}

export interface PresencePrintSpecs {
  bleedMm: Numeric | null;
  colorProfile: string | null;
  finish: Json | null;
  finishedHeightMm: Numeric | null;
  finishedWidthMm: Numeric | null;
  itemCode: string;
  minimumDpi: number | null;
  outputFormat: string | null;
  productName: string | null;
  safeAreaMm: Numeric | null;
  sourceUrl: string | null;
  supplier: string | null;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
}

export interface PresenceProductInclusions {
  itemCode: string;
  kind: string;
  label: string;
  personalized: Generated<boolean>;
  quantity: Generated<number>;
  sku: string;
  sortOrder: Generated<number>;
  version: number;
}

export interface PresenceProducts {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  name: string;
  priceCents: number | null;
  sku: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
  version: number;
}

export interface PresenceProfiles {
  bio: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  fullName: string | null;
  orderId: Int8;
  phone: string | null;
  updatedAt: Generated<Timestamp>;
  whatsapp: string;
}

export interface PresencePublicationArtifacts {
  artifactBytes: Int8;
  artifactHash: string;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  orderId: Int8;
  publishedAt: Timestamp | null;
  snapshotHash: string;
  status: Generated<string>;
  templateKey: string;
  templateVersion: number;
}

export interface PresenceServiceAreas {
  area: string;
  orderId: Int8;
}

export interface PresenceServices {
  orderId: Int8;
  serviceCode: string;
}

export interface PresenceShipments {
  deliveredAt: Timestamp | null;
  id: Generated<Int8>;
  orderId: Int8;
  postedAt: Timestamp | null;
  protocol: string | null;
  provider: Generated<string>;
  providerOrderId: string | null;
  status: Generated<string>;
  trackingCode: string | null;
  trackingUrl: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface PresenceShippingAddresses {
  city: string;
  complement: string | null;
  neighborhood: string;
  number: string;
  orderId: Int8;
  postalCode: string;
  state: string;
  street: string;
}

export interface PresenceShippingConfig {
  id: Generated<number>;
  originDocument: string | null;
  originEmail: string | null;
  originName: string | null;
  originPhone: string | null;
  originPostalCode: string | null;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  verifiedAt: Timestamp | null;
}

export interface PresenceShippingQuotes {
  companyName: string | null;
  createdAt: Generated<Timestamp>;
  deliveryDays: number | null;
  id: Generated<Int8>;
  orderId: Int8;
  priceCents: number;
  provider: Generated<string>;
  rawPayload: Json;
  selected: Generated<boolean>;
  serviceId: string;
  serviceName: string | null;
}

export interface PresenceShippingWebhookEvents {
  createdAt: Generated<Timestamp>;
  eventName: string;
  externalOrderId: string;
  id: Generated<Int8>;
  payload: Json;
  payloadHash: string;
  processedAt: Timestamp | null;
  processingResult: string | null;
  signatureValid: boolean;
}

export interface PresenceSnapshots {
  confirmedAt: Timestamp | null;
  content: Json;
  contentHash: string;
  createdAt: Generated<Timestamp>;
  id: Generated<Int8>;
  orderId: Int8;
  snapshotKind: string;
}

export interface PresenceSocialLinks {
  instagram: string | null;
  linkedin: string | null;
  orderId: Int8;
  tiktok: string | null;
  youtube: string | null;
}

export interface PresenceVehicles {
  brand: string;
  capacity: number | null;
  color: string;
  model: string;
  orderId: Int8;
  year: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  loginAttempts: LoginAttempts;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  presenceDriverPages: PresenceDriverPages;
  presenceGoogleBusiness: PresenceGoogleBusiness;
  presenceInventoryItems: PresenceInventoryItems;
  presenceOrderBomSnapshot: PresenceOrderBomSnapshot;
  presenceOrderEvents: PresenceOrderEvents;
  presenceOrderPersonalizations: PresenceOrderPersonalizations;
  presenceOrders: PresenceOrders;
  presencePackageSpecs: PresencePackageSpecs;
  presencePaymentAttempts: PresencePaymentAttempts;
  presencePaymentWebhookEvents: PresencePaymentWebhookEvents;
  presencePrintSpecs: PresencePrintSpecs;
  presenceProductInclusions: PresenceProductInclusions;
  presenceProducts: PresenceProducts;
  presenceProfiles: PresenceProfiles;
  presencePublicationArtifacts: PresencePublicationArtifacts;
  presenceServiceAreas: PresenceServiceAreas;
  presenceServices: PresenceServices;
  presenceShipments: PresenceShipments;
  presenceShippingAddresses: PresenceShippingAddresses;
  presenceShippingConfig: PresenceShippingConfig;
  presenceShippingQuotes: PresenceShippingQuotes;
  presenceShippingWebhookEvents: PresenceShippingWebhookEvents;
  presenceSnapshots: PresenceSnapshots;
  presenceSocialLinks: PresenceSocialLinks;
  presenceVehicles: PresenceVehicles;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.